2021-09-19 20:23:32,963 INFO    MainThread:16005 [wandb_setup.py:_flush():69] setting env: {}
2021-09-19 20:23:32,963 INFO    MainThread:16005 [wandb_setup.py:_flush():69] setting login settings: {}
2021-09-19 20:23:32,963 INFO    MainThread:16005 [wandb_setup.py:_flush():69] setting login settings: {}
2021-09-19 20:23:32,963 INFO    MainThread:16005 [wandb_init.py:_log_setup():342] Logging user logs to /home/hsyang/workspace/20210306_gan/smeg_gan_git/wandb/run-20210919_202332-1t8riy9v/logs/debug.log
2021-09-19 20:23:32,963 INFO    MainThread:16005 [wandb_init.py:_log_setup():343] Logging internal logs to /home/hsyang/workspace/20210306_gan/smeg_gan_git/wandb/run-20210919_202332-1t8riy9v/logs/debug-internal.log
2021-09-19 20:23:32,964 INFO    MainThread:16005 [wandb_init.py:_jupyter_setup():294] configuring jupyter hooks <wandb.sdk.wandb_init._WandbInit object at 0x7f2e9c23f7f0>
2021-09-19 20:23:32,965 INFO    MainThread:16005 [wandb_init.py:init():375] calling init triggers
2021-09-19 20:23:32,965 INFO    MainThread:16005 [wandb_init.py:init():380] wandb.init called with sweep_config: {}
config: {'device': 'cuda:1', 'epochs': 100, 'batch_size': 2048, 'img_size': 32, 'save_image_interval': 5, 'nz': 100, 'ngf': 64, 'ndf': 64, 'beta1': 0.5, 'latent_layer': 3, 'latent_dim': 10, 'n_iter': 3, 'project_name': 'SMEG GAN', 'dataset': 'cifar10', 'base_model': 'wgan', 'n_critic': 5, 'clip_value': 0.01, 'AE_iter': 10, 'smeg_gan': True, 'lr': 0.0001, 'run_test': False, 'dis_step': True, 'dis_layer': 8, 'wandb': True, 'sample_img_num': 16, 'force_gen_real_info': False, 'add_z_min': 0.0001, 'ae_end_conj': False, 'ae_end_diffloss': 0.01, 'use_plain_alpha': True}
2021-09-19 20:23:32,965 INFO    MainThread:16005 [wandb_init.py:init():424] starting backend
2021-09-19 20:23:32,965 INFO    MainThread:16005 [backend.py:_multiprocessing_setup():70] multiprocessing start_methods=fork,spawn,forkserver, using: spawn
2021-09-19 20:23:32,985 INFO    MainThread:16005 [backend.py:ensure_launched():135] starting backend process...
2021-09-19 20:23:33,003 INFO    MainThread:16005 [backend.py:ensure_launched():139] started backend process with pid: 16093
2021-09-19 20:23:33,004 INFO    MainThread:16005 [wandb_init.py:init():429] backend started and connected
2021-09-19 20:23:33,028 INFO    MainThread:16005 [wandb_run.py:_label_probe_notebook():815] probe notebook
2021-09-19 20:23:33,030 INFO    MainThread:16005 [wandb_run.py:_label_probe_notebook():822] Unable to probe notebook: 'NoneType' object has no attribute 'get'
2021-09-19 20:23:33,030 INFO    MainThread:16005 [wandb_init.py:init():477] updated telemetry
2021-09-19 20:23:33,031 INFO    MainThread:16005 [wandb_init.py:init():500] communicating current version
2021-09-19 20:23:33,745 INFO    MainThread:16005 [wandb_init.py:init():505] got version response upgrade_message: "wandb version 0.12.2 is available!  To upgrade, please run:\n $ pip install wandb --upgrade"

2021-09-19 20:23:33,747 INFO    MainThread:16005 [wandb_init.py:init():513] communicating run to backend with 30 second timeout
2021-09-19 20:23:34,047 INFO    MainThread:16005 [wandb_init.py:init():540] starting run threads in backend
2021-09-19 20:23:34,739 INFO    MainThread:16005 [wandb_run.py:_console_start():1601] atexit reg
2021-09-19 20:23:34,740 INFO    MainThread:16005 [wandb_run.py:_redirect():1475] redirect: SettingsConsole.WRAP
2021-09-19 20:23:34,741 INFO    MainThread:16005 [wandb_run.py:_redirect():1512] Wrapping output streams.
2021-09-19 20:23:34,742 INFO    MainThread:16005 [wandb_run.py:_redirect():1536] Redirects installed.
2021-09-19 20:23:34,742 INFO    MainThread:16005 [wandb_init.py:init():565] run started, returning control to user process
2021-09-19 20:23:36,132 INFO    MainThread:16005 [wandb_init.py:_pause_backend():256] pausing backend
2021-09-19 20:23:36,132 INFO    MainThread:16005 [jupyter.py:save_ipynb():298] not saving jupyter notebook
2021-09-19 20:23:36,139 INFO    MainThread:16005 [wandb_init.py:_resume_backend():265] resuming backend
2021-09-19 20:23:36,140 INFO    MainThread:16005 [wandb_init.py:_pause_backend():256] pausing backend
2021-09-19 20:23:36,141 INFO    MainThread:16005 [jupyter.py:save_ipynb():298] not saving jupyter notebook
2021-09-19 20:23:36,148 INFO    MainThread:16005 [wandb_init.py:_resume_backend():265] resuming backend
2021-09-19 20:23:36,152 INFO    MainThread:16005 [wandb_init.py:_pause_backend():256] pausing backend
2021-09-19 20:23:36,152 INFO    MainThread:16005 [jupyter.py:save_ipynb():298] not saving jupyter notebook
2021-09-19 20:23:36,159 INFO    MainThread:16005 [wandb_init.py:_resume_backend():265] resuming backend
2021-09-19 20:23:36,163 INFO    MainThread:16005 [wandb_init.py:_pause_backend():256] pausing backend
2021-09-19 20:23:36,163 INFO    MainThread:16005 [jupyter.py:save_ipynb():298] not saving jupyter notebook
2021-09-19 20:23:36,171 INFO    MainThread:16005 [wandb_init.py:_resume_backend():265] resuming backend
2021-09-19 20:23:36,174 INFO    MainThread:16005 [wandb_init.py:_pause_backend():256] pausing backend
2021-09-19 20:23:36,174 INFO    MainThread:16005 [jupyter.py:save_ipynb():298] not saving jupyter notebook
2021-09-19 20:23:36,189 INFO    MainThread:16005 [wandb_init.py:_resume_backend():265] resuming backend
2021-09-19 20:26:06,295 INFO    MainThread:16005 [wandb_init.py:_pause_backend():256] pausing backend
2021-09-19 20:26:06,295 INFO    MainThread:16005 [jupyter.py:save_ipynb():298] not saving jupyter notebook
2021-09-19 21:02:52,887 INFO    MainThread:16005 [wandb_run.py:_atexit_cleanup():1571] got exitcode: 0
2021-09-19 21:02:52,888 INFO    MainThread:16005 [wandb_run.py:_restore():1543] restore
